sudo: required
services:
  - docker

before_install:
  - docker build -t bnprashanth/poc-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true bnprashanth/poc-docker-kubernetes npm run test -- --coverage